org.gradle.jvmargs=-Xmx8192m -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
kotlin.daemon.jvmargs=-Xmx3072m
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true